name: 3.1 Contexts
# on: push
on: workflow_dispatch
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - run: echo "github.actor - ${{github.actor}}"
            - run: echo "github.run_id - ${{github.run_id}}"
#            - run: echo "github.head_ref - ${{github.head_ref}}"
            - run: echo "github.workspace - ${{github.workspace}}"
            - run: echo "github.repository - ${{github.repository}}"
            - run: echo "github.repository_owner - ${{github.repository_owner}}"
#            - run: echo "github.event - ${{github.event}}"
            - run: echo "runner.name - ${{runner.name}}"
            - run: echo "runner.os - ${{runner.os}}"
            - run: echo "runner.arch - ${{runner.arch}}"
            - run: echo "runner.temp - ${{runner.temp}}"
            - run: echo "runner.tool_cache - ${{runner.tool_cache}}"
