name: 3.2 Intermediate environment variables
# on: push
on: workflow_dispatch
jobs:
    print:
        runs-on: ubuntu-latest
        env:
            ACTOR: ${{github.actor}}
        steps:
            - run: echo "github.actor - ${ACTOR}"
