name: 3.2 Variables
# on: push
on: workflow_dispatch
jobs:
    print:
        runs-on: ubuntu-latest
        env:
            USERNAME: ${{vars.USERNAME}} # Variablesの参照
        steps:
            - run: echo "${USERNAME}"
