name: 3.4 Secrets
# on: push
on: workflow_dispatch
jobs:
    print:
        runs-on: ubuntu-latest
        env:
            SECRET_TEST: ${{secrets.SECRET_TEST}} # Secretsの参照
        steps:
            - run: echo "${SECRET_TEST}"                        # ログ出力はマスクされる
            - run: echo "${SECRET_TEST:0:1} ${SECRET_TEST#?}"   # ログ出力はマスクされない
