name: 3.6.4 Hash functions
# on: push
on: workflow_dispatch
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - run: echo "${HASH}"
            env:
              HASH: ${{ hashFiles('.github/workflows/*.yml') }}
