name: 3.7.1 Status check functions
# on: push
on: workflow_dispatch
jobs:
    fail:
        runs-on: ubuntu-latest
        steps:
            - run: exit 1
            - run: echo "Hello"
              if: ${{ failure() }}
