name: 3.7.2 Conditions workflow
# on: push
on: workflow_dispatch
jobs:
    skip-or-run:
        if: ${{ github.actor == 'archimedes' }}
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello"
