name: 3.7 Conditions
# on: push
on: workflow_dispatch
jobs:
    skip-or-run:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello"
              if: ${{ contains(github.run_id, '1') }} # ワークフロー実行IDで分岐
