name: 3.9.2 GITHUB_ENV
# on: push
on: workflow_dispatch
jobs:
    share:
        runs-on: ubuntu-latest
        steps:
            - run: echo "RESULT=Hello!!!" >> "${GITHUB_ENV}"  # GITHUB_ENVへ書き出し
            - run: echo "${RESULT}"                           # 通常の環境変数として参照
