name: 3.9.1 GITHUB_OUTPUT
# on: push
on: workflow_dispatch
jobs:
    share:
        runs-on: ubuntu-latest
        steps:
            - id: source                                        # ステップIDを設定
              run: echo "result=Hello!!!" >> "${GITHUB_OUTPUT}" # GITHUB_OUTPUTへ書き出し
            - env:
                RESULT: ${{ steps.source.outputs.result }}      # stepsコンテキストから参照
              run: echo "${RESULT}"
