name: 3.9 Missing share data
# on: push
on: workflow_dispatch
jobs:
    share:
        runs-on: ubuntu-latest
        steps:
            - run: export RESULT="hello"
            - run: echo "${RESULT}"
