name: 4.7 Change shell
# on: push
on: workflow_dispatch
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - shell: bash       # シェルにBashを指定
              run: echo "${SHELL}"
            - shell: python     # シェルにPythonを指定
              run: |
                import os
                print(os.environ['PATH'])
