name: 5.5.3 Share job data
# on: push
on: workflow_dispatch
jobs:
    before:
        runs-on: ubuntu-latest
        steps:
            - id: generate                                      # ステップのID
              run: echo "key=Value" >> "${GITHUB_OUTPUT}"    # ステップレベルの出力値
        outputs:
            result: ${{ steps.generate.outputs.key }}        # ジョブレベルの出力値
    after:
        runs-on: ubuntu-latest
        needs: [before]                                         # 依存するジョブIDの指定
        steps:
            - env:
                RESULT: ${{ needs.before.outputs.result }}      # 依存ジョブの出力値を参照
              run: echo "${RESULT}"
