name: 5.6.2 Manual matrix
# on: push
on: workflow_dispatch
jobs:
    print:
        strategy:
            matrix:
                include:                    # 組み合わせ条件を手動で列挙
                    - os: utunbu-latest     # パターン1
                      version: 20
                    - os: macos-latest      # パターン2
                      version: 18
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.version }}
            - run: echo "${RUNNER_OS}" && node --version
